title: AIS Development Portal
email: ahmad.infinite.services@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  AIS Development Portal is an information site for repositories and development documentation used by AIS development team.
  This site is created to encourage the sharing of information and documentation of development tools and processes used by the AIS umbrella.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  ais-developer

github: [metadata]

sass:
  sass_dir: _sass
  style: compact

plugins:
  - jekyll-coffeescript